<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>aggr-meta-builder</artifactId>
    <version>1.0.1</version>
    <parent>
        <groupId>tools.cipm</groupId>
        <artifactId>builder-site</artifactId>
        <version>1.0.0</version>
    </parent>
    
    <repositories>
        <repository>
            <id>cipm-mvn</id>
            <name>CIPM's Maven Repository</name>
            <url>https://CIPM-tools.github.io/updatesite/mvn</url>
        </repository>
    </repositories>
    
    <build>
        <plugins>
            <plugin>
                <groupId>org.reficio</groupId>
                <artifactId>p2-maven-plugin</artifactId>
                <version>2.1.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>site</goal>
                        </goals>
                        <configuration>
                            <categoryFileURL>${project.basedir}/src/category.xml</categoryFileURL>
                            <artifacts>
                                <!-- specify your depencies here -->
                                <!-- groupId:artifactId:version -->
                                <artifact>
                                    <id>tools.mdsd:org.emftext.language.java:5.1.0-cipm</id>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>tools.cipm:org.xtext.lua:0.1.0</id>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>tools.cipm:tools.cipm.models.instrumentation:1.0.1</id>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.palladiosimulator.core:org.palladiosimulator.pcm:5.0.0.202102051710</id>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.palladiosimulator.commons:de.uka.ipd.sdq.identifier:5.0.0.202102051655</id>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.palladiosimulator.commons:de.uka.ipd.sdq.probfunction:5.0.0.202102051655</id>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.palladiosimulator.commons:de.uka.ipd.sdq.units:5.0.0.202102051655</id>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.palladiosimulator.commons:de.uka.ipd.sdq.stoex:5.0.0.202102051655</id>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.palladiosimulator.commons:de.uka.ipd.sdq.errorhandling:5.0.0.202102051655</id>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.palladiosimulator.commons:org.palladiosimulator.commons:5.0.0.202102051655</id>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.palladiosimulator.commons:org.palladiosimulator.commons.stoex.api:5.0.0.202102051655</id>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.palladiosimulator.commons:org.palladiosimulator.commons.stoex:5.0.0.202102051655</id>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.palladiosimulator.commons:de.uka.ipd.sdq.stoex.analyser:5.0.0.202102051655</id>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.palladiosimulator.commons:de.uka.ipd.sdq.probfunction.math:5.0.0.202102051655</id>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.apache.commons:commons-math:2.1</id>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.eclipse.emf.cdo:org.eclipse.emf.cdo:4.19.0.v20220907-1437</id>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.eclipse.emf.cdo:org.eclipse.emf.cdo.common:4.19.0.v20220907-1437</id>
                                    <transitive>false</transitive>
                                </artifact>
                                <artifact>
                                    <id>org.eclipse.net4j:org.eclipse.net4j.util:3.20.0.v20220907-1437</id>
                                    <transitive>false</transitive>
                                </artifact>
                            </artifacts>
                            <featureDefinitions>
                                <feature>
                                    <id>tools.cipm.metamodels.aggregated.feature</id>
                                    <version>${project.version}</version>
                                    <label>CIPM's Aggregated Metamodels</label>
                                    <providerName>MCSE</providerName>
                                    <description>Aggregated metamodels for CIPM.</description>
                                    <copyright>
                                        This aggregated update site contains multiple artefacts with different licenses and copyright holders.
                                    </copyright>
                                    <license>
                                        This aggregated update site contains multiple artefacts with different licenses and copyright holders. The licenses include the Eclipse Public License v1.0, Eclipse Public License 2.0, and Apache License 2.0.
                                    </license>
                                    <generateSourceFeature>false</generateSourceFeature>
                                    <artifacts>
                                        <artifact>
                                            <id>tools.mdsd:org.emftext.language.java:5.1.0-cipm</id>
                                            <transitive>false</transitive>
                                            <source>false</source>
                                        </artifact>
                                        <artifact>
                                            <id>tools.cipm:org.xtext.lua:0.1.0</id>
                                            <transitive>false</transitive>
                                            <source>false</source>
                                        </artifact>
                                        <artifact>
                                            <id>tools.cipm:tools.cipm.models.instrumentation:1.0.1</id>
                                            <transitive>false</transitive>
                                            <source>false</source>
                                        </artifact>
                                        <artifact>
                                            <id>org.palladiosimulator.core:org.palladiosimulator.pcm:5.0.0.202102051710</id>
                                            <transitive>false</transitive>
                                            <source>false</source>
                                        </artifact>
                                        <artifact>
                                            <id>org.palladiosimulator.commons:de.uka.ipd.sdq.identifier:5.0.0.202102051655</id>
                                            <transitive>false</transitive>
                                            <source>false</source>
                                        </artifact>
                                        <artifact>
                                            <id>org.palladiosimulator.commons:de.uka.ipd.sdq.probfunction:5.0.0.202102051655</id>
                                            <transitive>false</transitive>
                                            <source>false</source>
                                        </artifact>
                                        <artifact>
                                            <id>org.palladiosimulator.commons:de.uka.ipd.sdq.units:5.0.0.202102051655</id>
                                            <transitive>false</transitive>
                                            <source>false</source>
                                        </artifact>
                                        <artifact>
                                            <id>org.palladiosimulator.commons:de.uka.ipd.sdq.stoex:5.0.0.202102051655</id>
                                            <transitive>false</transitive>
                                            <source>false</source>
                                        </artifact>
                                        <artifact>
                                            <id>org.palladiosimulator.commons:de.uka.ipd.sdq.errorhandling:5.0.0.202102051655</id>
                                            <transitive>false</transitive>
                                            <source>false</source>
                                        </artifact>
                                        <artifact>
                                            <id>org.palladiosimulator.commons:org.palladiosimulator.commons:5.0.0.202102051655</id>
                                            <transitive>false</transitive>
                                            <source>false</source>
                                        </artifact>
                                        <artifact>
                                            <id>org.palladiosimulator.commons:org.palladiosimulator.commons.stoex.api:5.0.0.202102051655</id>
                                            <transitive>false</transitive>
                                            <source>false</source>
                                        </artifact>
                                        <artifact>
                                            <id>org.palladiosimulator.commons:org.palladiosimulator.commons.stoex:5.0.0.202102051655</id>
                                            <transitive>false</transitive>
                                            <source>false</source>
                                        </artifact>
                                        <artifact>
                                            <id>org.palladiosimulator.commons:de.uka.ipd.sdq.stoex.analyser:5.0.0.202102051655</id>
                                            <transitive>false</transitive>
                                            <source>false</source>
                                        </artifact>
                                        <artifact>
                                            <id>org.palladiosimulator.commons:de.uka.ipd.sdq.probfunction.math:5.0.0.202102051655</id>
                                            <transitive>false</transitive>
                                            <source>false</source>
                                        </artifact>
                                        <artifact>
                                            <id>org.apache.commons:commons-math:2.1</id>
                                            <transitive>false</transitive>
                                            <source>false</source>
                                        </artifact>
                                        <artifact>
                                            <id>org.eclipse.emf.cdo:org.eclipse.emf.cdo:4.19.0.v20220907-1437</id>
                                            <transitive>false</transitive>
                                            <source>false</source>
                                        </artifact>
                                        <artifact>
                                            <id>org.eclipse.emf.cdo:org.eclipse.emf.cdo.common:4.19.0.v20220907-1437</id>
                                            <transitive>false</transitive>
                                            <source>false</source>
                                        </artifact>
                                        <artifact>
                                            <id>org.eclipse.net4j:org.eclipse.net4j.util:3.20.0.v20220907-1437</id>
                                            <transitive>false</transitive>
                                            <source>false</source>
                                        </artifact>
                                    </artifacts>                           
                                </feature>
                            </featureDefinitions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <descriptors>
                        <descriptor>src/assembly/src.xml</descriptor>
                    </descriptors>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    
    <!-- The dependencies are to make sure this project is build after all relevant artifacts are created. -->
    <dependencies>
        <dependency>
            <groupId>org.palladiosimulator.core</groupId>
            <artifactId>org.palladiosimulator.pcm</artifactId>
            <version>5.0.0.202102051710</version>
        </dependency>
        <dependency>
            <groupId>org.palladiosimulator.commons</groupId>
            <artifactId>de.uka.ipd.sdq.identifier</artifactId>
            <version>5.0.0.202102051655</version>
        </dependency>
        <dependency>
            <groupId>org.palladiosimulator.commons</groupId>
            <artifactId>de.uka.ipd.sdq.probfunction</artifactId>
            <version>5.0.0.202102051655</version>
        </dependency>
        <dependency>
            <groupId>org.palladiosimulator.commons</groupId>
            <artifactId>de.uka.ipd.sdq.units</artifactId>
            <version>5.0.0.202102051655</version>
        </dependency>
        <dependency>
            <groupId>org.palladiosimulator.commons</groupId>
            <artifactId>de.uka.ipd.sdq.stoex</artifactId>
            <version>5.0.0.202102051655</version>
        </dependency>
        <dependency>
            <groupId>org.palladiosimulator.commons</groupId>
            <artifactId>de.uka.ipd.sdq.errorhandling</artifactId>
            <version>5.0.0.202102051655</version>
        </dependency>
        <dependency>
            <groupId>org.palladiosimulator.commons</groupId>
            <artifactId>org.palladiosimulator.commons.stoex.api</artifactId>
            <version>5.0.0.202102051655</version>
        </dependency>
        <dependency>
            <groupId>org.palladiosimulator.commons</groupId>
            <artifactId>org.palladiosimulator.commons.stoex</artifactId>
            <version>5.0.0.202102051655</version>
        </dependency>
        <dependency>
            <groupId>org.palladiosimulator.commons</groupId>
            <artifactId>de.uka.ipd.sdq.stoex.analyser</artifactId>
            <version>5.0.0.202102051655</version>
        </dependency>
        <dependency>
            <groupId>org.palladiosimulator.commons</groupId>
            <artifactId>org.palladiosimulator.commons</artifactId>
            <version>5.0.0.202102051655</version>
        </dependency>
        <dependency>
            <groupId>org.palladiosimulator.commons</groupId>
            <artifactId>de.uka.ipd.sdq.probfunction.math</artifactId>
            <version>5.0.0.202102051655</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf.cdo</groupId>
            <artifactId>org.eclipse.emf.cdo</artifactId>
            <version>4.19.0.v20220907-1437</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.emf.cdo</groupId>
            <artifactId>org.eclipse.emf.cdo.common</artifactId>
            <version>4.19.0.v20220907-1437</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.net4j</groupId>
            <artifactId>org.eclipse.net4j.util</artifactId>
            <version>3.20.0.v20220907-1437</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-math</artifactId>
            <version>2.1</version>
        </dependency>
        <dependency>
            <groupId>tools.mdsd</groupId>
            <artifactId>org.emftext.language.java</artifactId>
            <version>5.1.0-cipm</version>
        </dependency>
        <dependency>
            <groupId>tools.cipm</groupId>
            <artifactId>org.xtext.lua</artifactId>
            <version>0.1.0</version>
        </dependency>
        <dependency>
            <groupId>tools.cipm</groupId>
            <artifactId>tools.cipm.models.instrumentation</artifactId>
            <version>1.0.1</version>
        </dependency>
    </dependencies>
</project>